api:
  url: "http://192.168.1.69"
  application-key: "Z7umYfcyoBe2oJbJvP4SOEol8E5qYCI7GjY33f4lJkV8ImXt"
  user-key: "pn6gNa9Fhsa9CfOxZ9qdOLDsivIytg2NDJs9uTewTsDW3bwA"

allocations:
  ip: "192.168.1.56"
  port-range: "25665-25699"

server-templates:
  example1:
    display-name: "Example 1"
    max-servers: 3
    server-settigs:
      core-details:
        owner-id: 2
        name: "{username}`s server"
        node-id: 1
      application-feature-limits:
        database-limit: 1
        allocation-limit: 1
        backup-limit: 1
      resource-management:
        memory: 128
        swap: 0
        disk-space: 512
        block-io-weight: 500
        cpu-limit: 100
        cpu-pinning: "" #"0-1,3"
        enable-oom: false
      egg-id: 1
      docker-image: "ghcr.io/pterodactyl/yolks:java_17"
      startup-command: "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar server.jar"
    backup-settings:
      cronjob-syntax: "*/5 * * *"
      ignore:
        - "server.jar"
        - "/logs"

messages:
  # INGAME
  config-reload-successful: "&aConfiguration reloaded successfully"
  config-reload-failed: "&cThere was an error reloading the configuration"
  config-template-not-exists: "&cThat template doesn't exist"

  # CONSOLE
  request-403: "Server responded with a 403 - Forbidden. Please check the keys in config.yml"
  request-404: "Server responded with a 404 - Not found. Please check the URL in config.yml"
  connection-error-generic: "There was an error while trying to connect to the server. Please check the config.yml"
