api:
  url: "http://192.168.1.69"
  application-key: "Z7umYfcyoBe2oJbJvP4SOEol8E5qYCI7GjY33f4lJkV8ImXt"
  user-key: "pn6gNa9Fhsa9CfOxZ9qdOLDsivIytg2NDJs9uTewTsDW3bwA"

allocations:
  ip: "192.168.1.56"
  port-range: "25665-25699"

server-templates:
  example1:
    display-name: "Example 1"
    max-servers: 3
    server-settigs:
      core-details:
        owner-id: 2
        name: "{username}`s server"
      allocation-management:
        node-id: 1
        allocations: 1
      application-feature-limits:
        backup-limit: 1
      resource-management:
        memory: 128
        swap: 0
        disk-space: 512
        block-io-weight: 500
        cpu-limit: 100
        cpu-pinning: null #"0-1,3"
        enable-oom: false
      egg-id: 1
      docker-image: "ghcr.io/pterodactyl/yolks:java_17"
    backup-settings:
      cronjob-syntax: "*/5 * * *"
      ignore:
        - "server.jar"
        - "/logs"

messages:
  config-reload-successful: "&aConfiguration reloaded successfully"
  config-reload-failed: "&cThere was an error reloading the configuration"
